### PR TITLE
Pin pyparsing

### PR DESCRIPTION
**Pull request by krassowski**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Follow up after #20

Hey, the [**only**](https://github.com/pypa/packaging/compare/21.1...21.2) change in v21.2 was in this version pin.

### CODE REVIEW

**Comment by krassowski** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Oops. Thanks for the fix!

**Comment by jakirkham** [comment]
We will need a repodata hotfix as well

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

**Comment by krassowski** [comment]
FYI there is some discussion about this pin: https://github.com/pypa/packaging/pull/471#issuecomment-954713724 and some suggestions to yank this patch release.

**Comment by jakirkham** [comment]
Interesting, thanks for sharing that

**Comment by beckermr** [comment]
In the meantime can we mark both versions as broken? We can unbreak them later.

**Comment by jakirkham** [comment]
Submitted a hot-fix in PR ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/176 )

**Comment by jakirkham** [comment]
Sure I don't have strong feelings

**Comment by beckermr** [comment]
oh nvm. a package pin fix is great!

**Comment by jakirkham** [comment]
Ok 🙂

If we change our minds, we can always do something different 😉

**Comment by maresb** [comment]
Hi all, I'm trying to understand how [repodata-patches](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/dd13f6b26ab66452f4ef168444f2a7ad61fcc108) works. I was wondering what is the purpose of bumping the build number in this case? I think it should be unnecessary since

1. the dependencies were modified in the repodata
2. changing the tests shouldn't modify the build

Did bumping the version number accomplish anything in this case? Just trying to understand, thanks!

**Comment by chrisburr** [comment]
> Did bumping the version number accomplish anything in this case? Just trying to understand, thanks!

@maresb Your understanding is correct.

The main reason it's nice to update the recipe to make debugging easier and without it it's easy to check the feedstock, find the dependency is correct and the build number is 0 and then not realise build 0 was deployed from a different commit. (The truth can always be determined from the `info` directory but that's less convenient than GitHub)

**Comment by tpdownes** [comment]
Is there any way to yank the packaging=21.0 packages?

```shell
$ conda update --name default --all --yes
Collecting package metadata (current_repodata.json): done
Solving environment: -
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge/noarch::packaging-21.0-pyhd8ed1ab_0, conda-forge/noarch::pyparsing-3.0.6-pyhd8ed1ab_0
  - conda-forge/noarch::packaging-21.2-pyhd8ed1ab_1, conda-forge/noarch::pyparsing-2.4.7-pyhd8ed1abdone
```

while it makes the right choice in my case, it still leaves a known invalid combination in the wild. Plus this annoying warning, possibly forever?

UPDATE: I take it back. I have to manually force a downgrade of `pyparsing` with

```shell
$ conda install packaging=21.2
```

and then the warning goes away. I'm not sure what the right action, if any, is for the `conda-forge` repo itself.

**Pull request merged**
